version: '3.8'

services:
  web:
    build: .
    command: pipenv run python ./multipledatabases/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/project/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
