services:
  mongo:
    image: mongo
    expose:
      - 3306
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=poc-prodrducts
    volumes:
      - mongo_data:/var/lib/mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: poc
      MYSQL_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql
    depends_on:
      - mongo

  django:
    build: .
    command:
      - sh
      - -c
      - "pipenv run python ./multipledatabases/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/project/
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - mongo
      - mysql

volumes:
  mongo_data:
  mysql_data:
